const localJson = [
    {
        "Cliente": "John Doe",
        "Vendedor": "Jane Smith",
        "Fecha": "2023-05-01",
        "Tdoc": "REC 93",
        "Ndoc": "00001",
        "Cuenta": "A",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Alice Johnson",
        "Vendedor": "Bob Brown",
        "Fecha": "2023-05-02",
        "Tdoc": "REC 93",
        "Ndoc": "00002",
        "Cuenta": "U",
        "Cantidad": 1,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": "Lorem ipsum dolor sit amet."
    },
    {
        "Cliente": "Charlie Williams",
        "Vendedor": "David Miller",
        "Fecha": "2023-05-03",
        "Tdoc": "REC 93",
        "Ndoc": "00003",
        "Cuenta": "Q",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Eve Wilson",
        "Vendedor": "Frank Moore",
        "Fecha": "2023-05-04",
        "Tdoc": "REC 93",
        "Ndoc": "00004",
        "Cuenta": "A",
        "Cantidad": 1,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Grace Taylor",
        "Vendedor": "Henry Anderson",
        "Fecha": "2023-05-05",
        "Tdoc": "REC 93",
        "Ndoc": "00005",
        "Cuenta": "U",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": "Consectetur adipiscing elit."
    },
    {
        "Cliente": "Ivy Thomas",
        "Vendedor": "Jack Martin",
        "Fecha": "2023-05-06",
        "Tdoc": "REC 93",
        "Ndoc": "00006",
        "Cuenta": "Q",
        "Cantidad": 1,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Kate Martinez",
        "Vendedor": "Leo Hernandez",
        "Fecha": "2023-05-07",
        "Tdoc": "REC 93",
        "Ndoc": "00007",
        "Cuenta": "A",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Mia Garcia",
        "Vendedor": "Nick Lopez",
        "Fecha": "2023-05-08",
        "Tdoc": "REC 93",
        "Ndoc": "00008",
        "Cuenta": "U",
        "Cantidad": 1,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Oscar Lee",
        "Vendedor": "Paul Clark",
        "Fecha": "2023-05-09",
        "Tdoc": "REC 93",
        "Ndoc": "00009",
        "Cuenta": "Q",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Quinn Walker",
        "Vendedor": "Rachel Lewis",
        "Fecha": "2023-05-10",
        "Tdoc": "REC 93",
        "Ndoc": "00010",
        "Cuenta": "A",
        "Cantidad": 1,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Sophie Young",
        "Vendedor": "Thomas Hall",
        "Fecha": "2023-05-11",
        "Tdoc": "REC 93",
        "Ndoc": "00011",
        "Cuenta": "Q",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Uma King",
        "Vendedor": "Victor Wright",
        "Fecha": "2023-05-12",
        "Tdoc": "REC 93",
        "Ndoc": "00012",
        "Cuenta": "U",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": "Excepteur sint occaecat cupidatat non proident."
    },
    {
        "Cliente": "Walter Young",
        "Vendedor": "Xander Hall",
        "Fecha": "2023-05-13",
        "Tdoc": "REC 93",
        "Ndoc": "00013",
        "Cuenta": "A",
        "Cantidad": 1,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Yara Diaz",
        "Vendedor": "Zachary Kim",
        "Fecha": "2023-05-14",
        "Tdoc": "REC 93",
        "Ndoc": "00014",
        "Cuenta": "Q",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Aaron Foster",
        "Vendedor": "Bella Evans",
        "Fecha": "2023-05-15",
        "Tdoc": "REC 93",
        "Ndoc": "00015",
        "Cuenta": "U",
        "Cantidad": 1,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Caleb Howard",
        "Vendedor": "Dana Morgan",
        "Fecha": "2023-05-16",
        "Tdoc": "REC 93",
        "Ndoc": "00016",
        "Cuenta": "A",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Eli Carter",
        "Vendedor": "Fiona Murphy",
        "Fecha": "2023-05-17",
        "Tdoc": "REC 93",
        "Ndoc": "00017",
        "Cuenta": "Q",
        "Cantidad": 1,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "George King",
        "Vendedor": "Holly Wright",
        "Fecha": "2023-05-18",
        "Tdoc": "REC 93",
        "Ndoc": "00018",
        "Cuenta": "U",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam."
    },
    {
        "Cliente": "Ivy Nelson",
        "Vendedor": "Jack Lee",
        "Fecha": "2023-05-19",
        "Tdoc": "REC 93",
        "Ndoc": "00019",
        "Cuenta": "A",
        "Cantidad": 1,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Karen Hill",
        "Vendedor": "Liam Young",
        "Fecha": "2023-05-20",
        "Tdoc": "REC 93",
        "Ndoc": "00020",
        "Cuenta": "Q",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Michael White",
        "Vendedor": "Nancy Scott",
        "Fecha": "2023-05-21",
        "Tdoc": "REC 93",
        "Ndoc": "00021",
        "Cuenta": "U",
        "Cantidad": 1,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Olivia Taylor",
        "Vendedor": "Paul Martinez",
        "Fecha": "2023-05-22",
        "Tdoc": "REC 93",
        "Ndoc": "00022",
        "Cuenta": "A",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Quinn Robinson",
        "Vendedor": "Rachel Harris",
        "Fecha": "2023-05-23",
        "Tdoc": "REC 93",
        "Ndoc": "00023",
        "Cuenta": "Q",
        "Cantidad": 1,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    },
    {
        "Cliente": "Sophia Clark",
        "Vendedor": "Thomas Walker",
        "Fecha": "2023-05-24",
        "Tdoc": "REC 93",
        "Ndoc": "00024",
        "Cuenta": "U",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Tyler Lewis",
        "Vendedor": "Uma King",
        "Fecha": "2023-05-25",
        "Tdoc": "REC 93",
        "Ndoc": "00025",
        "Cuenta": "A",
        "Cantidad": 1,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Victoria Hernandez",
        "Vendedor": "Willie Martin",
        "Fecha": "2023-05-26",
        "Tdoc": "REC 93",
        "Ndoc": "00026",
        "Cuenta": "Q",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Xavier Brown",
        "Vendedor": "Yary Young",
        "Fecha": "2023-05-27",
        "Tdoc": "REC 93",
        "Ndoc": "00027",
        "Cuenta": "U",
        "Cantidad": 1,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    },
    {
        "Cliente": "Aaron Foster",
        "Vendedor": "Bella Evans",
        "Fecha": "2023-05-28",
        "Tdoc": "REC 93",
        "Ndoc": "00028",
        "Cuenta": "A",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    },
    {
        "Cliente": "Caleb Howard",
        "Vendedor": "Dana Morgan",
        "Fecha": "2023-05-29",
        "Tdoc": "REC 93",
        "Ndoc": "00029",
        "Cuenta": "Q",
        "Cantidad": 1,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam."
    },
    {
        "Cliente": "Eli Carter",
        "Vendedor": "Fiona Murphy",
        "Fecha": "2023-05-30",
        "Tdoc": "REC 93",
        "Ndoc": "00030",
        "Cuenta": "U",
        "Cantidad": 2,
        "Descripcion": "ARETES - JOYARE 21696",
        "Comentario": ""
    }
]
